### ISSUE TITLE
Rotação de tela

### ISSUE THREAD

**Issue by alexandre-mbm** [alexandre-mbm/rotyad#1]
@alandbm, mande-me os 4 arquivos de `xandr` que você tem. Pode anexá-los ao comentário ou somente me transmitir os comandos que, em cada um deles, mais importam.

**Comment by alexandre-mbm** [comment]
O comandos foram recebidos e-mail. De qualquer forma, o presente projeto [rotyad](/alexandre-mbm/rotyad) está sendo remodelado. Não temos mais a intenção de "criar algo", apenas faremos estudos aqui, e aperfeiçoaremos coisas em nosso fork [InspironAutoRotateService](/alexandre-mbm/InspironAutoRotateService).

---

### Uma pergunta sobre o `xrandr`

@alandbm, neste comando:

``` sh
xrandr --output eDP1 --rotate normal
```

Como você descobriu que tinha de ser `eDP1`?

**Comment by alexandre-mbm** [comment]
Nosso fork [InspironAutoRotateService](/alexandre-mbm/InspironAutoRotateService) tem resolvida a questão da rotação de tela.

**Comment by alandbm** [comment]
> Como você descobriu que tinha de ser `eDP1`?

``` console
$ xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 293mm x 165mm
   1920x1080      60.0*+   59.9     48.0  
   1680x1050      60.0     59.9  
   1600x1024      60.2  
   1400x1050      60.0  
   1280x1024      60.0  
   1440x900       59.9  
   1280x960       60.0  
   1360x768       59.8     60.0  
   1152x864       60.0  
   1024x768       60.0  
   800x600        60.3     56.2  
   640x480        59.9  
HDMI1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```
